apiVersion: v1
kind: Service
metadata:
  name: my-api-service
  namespace: my-api
spec:
  type: NodePort
  selector:
    app: my-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
